version: '3.8'


volumes:
  db-data:
    driver:local


services:
  app:
    build:
      context: ../myproject
      dockerfile: ../docker/php/Dockerfile
    restart: unless-stopped
    env_file:
      - ../docker/.env
    expose:
      - ${Php_Exp_port}
    container_name: my-app
    volumes:
      - ../myproject:/www'

  # --- server - 'nginx' ---
  nginx:
    image: nginx:1.19-alpine
    container_name: my-nginx
    restart: unless-stopped
    volumes:
      - '../myproject:/www'
      -  '../docker/nginx/conf.d:/etc/nginx/conf.d'
    ports:
      - '${Nginx_port}:80'


  # --- database - 'postgresql' ---
  postgres:
    image: postgres:9.6
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ../docker/.env
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    ports:
      - "5432:5432"

  # --- database environment - 'adminer' ---
  adminer:
    image: adminer
    restart: unless-stopped
    env_file:
      - ../docker/.env
    ports:
      - '${Adminer_port}:8080'
