version: '3.8'

services:
  app:
    build: /docker/php
    restart: unless-stopped
    expose:
      - 9000
    container_name: my-app
    volumes:
      - './src/public:/var/www/html'
  # --- server - 'nginx' ---
  nginx:
    image: nginx:1.19-alpine
    container_name: my-nginx
    restart: unless-stopped
    volumes:
      - './src/public:/var/www/html'
      -  './docker/nginx/conf.d:/etc/nginx/conf.d'
    ports:
      - 8000:80


  # --- database - 'mysql' ---
  postgres:
    image: postgres:9.6
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./docker/.env


  # --- database environment - 'adminer' ---
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
